// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MobileTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Logging in to mobile site
        /// </summary>
        public void Login()
        {
            #region Variable Declarations
            WinControl uIChromeLegacyWindowDocument = this.UILogInGoogleChromeWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            WinCustom uIItemCustom = this.UILogInGoogleChromeWindow.UIChromeLegacyWindowWindow.UIItemCustom;
            WinCustom uIItemCustom1 = this.UILogInGoogleChromeWindow.UIChromeLegacyWindowWindow.UIItemCustom1;
            #endregion

            // Move 'Chrome Legacy Window' document
            Mouse.StartDragging(uIChromeLegacyWindowDocument, new Point(1054, 366));
            Mouse.StopDragging(uIChromeLegacyWindowDocument, -376, 14);

            // Type '{Back}cgpuglie{Tab}' in custom control
            Keyboard.SendKeys(uIItemCustom, this.LoginParams.UIItemCustomSendKeys, ModifierKeys.None);

            // Type 'password' in custom control
            Keyboard.SendKeys(uIItemCustom1, this.LoginParams.UIItemCustom1SendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// Loggin in through IE, hopefully it works :)
        /// </summary>
        public void NewLogin()
        {

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.
        }
        
        /// <summary>
        /// Try going to the desktop site
        /// </summary>
        public void GoToDesktopSite()
        {
            #region Variable Declarations
            WinClient uINavigationBarClient = this.UISelectaformInternetEWindow.UIItemWindow.UINavigationBarClient;
            BrowserWindow uISelectaformInternetEWindow = this.UISelectaformInternetEWindow;
            #endregion

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Last mouse action was not recorded.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Click 'Navigation Bar' client
            Mouse.Click(uINavigationBarClient, new Point(-325, 7));

            // Move 'Navigation Bar' client
            Mouse.StartDragging(uINavigationBarClient, new Point(-214, 18));
            Mouse.StopDragging(uINavigationBarClient, -139, -7);

            // Go to web page 'http://localhost:2424/Desktop/Login.aspx'
            uISelectaformInternetEWindow.NavigateToUrl(new System.Uri(this.GoToDesktopSiteParams.UISelectaformInternetEWindowUrl));
        }
        
        /// <summary>
        /// login and submit form
        /// </summary>
        public void LoginAndSubmit()
        {
            #region Variable Declarations
            WpfMenuItem uIDebugTargetMenuItem = this.UISDFCDebuggingMicrosoWindow.UIDebugTargetMenu.UIDebugTargetMenuItem;
            #endregion

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Internet Explorer zoom setting must be set to 100%. Please change the value to 100% and try again.

            // Click 'Debug Target' menu item
            Mouse.Click(uIDebugTargetMenuItem, new Point(79, 23));
        }
        
        #region Properties
        public virtual LoginParams LoginParams
        {
            get
            {
                if ((this.mLoginParams == null))
                {
                    this.mLoginParams = new LoginParams();
                }
                return this.mLoginParams;
            }
        }
        
        public virtual GoToDesktopSiteParams GoToDesktopSiteParams
        {
            get
            {
                if ((this.mGoToDesktopSiteParams == null))
                {
                    this.mGoToDesktopSiteParams = new GoToDesktopSiteParams();
                }
                return this.mGoToDesktopSiteParams;
            }
        }
        
        public UILogInGoogleChromeWindow UILogInGoogleChromeWindow
        {
            get
            {
                if ((this.mUILogInGoogleChromeWindow == null))
                {
                    this.mUILogInGoogleChromeWindow = new UILogInGoogleChromeWindow();
                }
                return this.mUILogInGoogleChromeWindow;
            }
        }
        
        public UISelectaformInternetEWindow UISelectaformInternetEWindow
        {
            get
            {
                if ((this.mUISelectaformInternetEWindow == null))
                {
                    this.mUISelectaformInternetEWindow = new UISelectaformInternetEWindow();
                }
                return this.mUISelectaformInternetEWindow;
            }
        }
        
        public UISDFCDebuggingMicrosoWindow UISDFCDebuggingMicrosoWindow
        {
            get
            {
                if ((this.mUISDFCDebuggingMicrosoWindow == null))
                {
                    this.mUISDFCDebuggingMicrosoWindow = new UISDFCDebuggingMicrosoWindow();
                }
                return this.mUISDFCDebuggingMicrosoWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginParams mLoginParams;
        
        private GoToDesktopSiteParams mGoToDesktopSiteParams;
        
        private UILogInGoogleChromeWindow mUILogInGoogleChromeWindow;
        
        private UISelectaformInternetEWindow mUISelectaformInternetEWindow;
        
        private UISDFCDebuggingMicrosoWindow mUISDFCDebuggingMicrosoWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Login'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class LoginParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{Back}cgpuglie{Tab}' in custom control
        /// </summary>
        public string UIItemCustomSendKeys = "{Back}cgpuglie{Tab}";
        
        /// <summary>
        /// Type 'password' in custom control
        /// </summary>
        public string UIItemCustom1SendKeys = "password";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'GoToDesktopSite'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class GoToDesktopSiteParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:2424/Desktop/Login.aspx'
        /// </summary>
        public string UISelectaformInternetEWindowUrl = "http://localhost:2424/Desktop/Login.aspx";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UILogInGoogleChromeWindow : WinWindow
    {
        
        public UILogInGoogleChromeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "log In - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("log In - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "274736192";
            this.WindowTitles.Add("log In - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("log In - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("log In - Google Chrome");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.WindowTitles.Add("log In - Google Chrome");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        
        private WinCustom mUIItemCustom;
        
        private WinCustom mUIItemCustom1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISelectaformInternetEWindow : BrowserWindow
    {
        
        public UISelectaformInternetEWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "select a form";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("select a form");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("select a form");
            #endregion
        }
        
        #region Properties
        public WinClient UINavigationBarClient
        {
            get
            {
                if ((this.mUINavigationBarClient == null))
                {
                    this.mUINavigationBarClient = new WinClient(this);
                    #region Search Criteria
                    this.mUINavigationBarClient.WindowTitles.Add("select a form");
                    #endregion
                }
                return this.mUINavigationBarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUINavigationBarClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISDFCDebuggingMicrosoWindow : WpfWindow
    {
        
        public UISDFCDebuggingMicrosoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "SDFC (Debugging) - Microsoft Visual Studio (Administrator)";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("SDFC (Debugging) - Microsoft Visual Studio (Administrator)");
            #endregion
        }
        
        #region Properties
        public UIDebugTargetMenu UIDebugTargetMenu
        {
            get
            {
                if ((this.mUIDebugTargetMenu == null))
                {
                    this.mUIDebugTargetMenu = new UIDebugTargetMenu(this);
                }
                return this.mUIDebugTargetMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIDebugTargetMenu mUIDebugTargetMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIDebugTargetMenu : WpfMenu
    {
        
        public UIDebugTargetMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfMenu.PropertyNames.Name] = "Debug Target";
            this.WindowTitles.Add("SDFC (Debugging) - Microsoft Visual Studio (Administrator)");
            #endregion
        }
        
        #region Properties
        public WpfMenuItem UIDebugTargetMenuItem
        {
            get
            {
                if ((this.mUIDebugTargetMenuItem == null))
                {
                    this.mUIDebugTargetMenuItem = new WpfMenuItem(this);
                    #region Search Criteria
                    this.mUIDebugTargetMenuItem.SearchProperties[WpfMenuItem.PropertyNames.AutomationId] = "PART_FocusTarget";
                    this.mUIDebugTargetMenuItem.WindowTitles.Add("SDFC (Debugging) - Microsoft Visual Studio (Administrator)");
                    #endregion
                }
                return this.mUIDebugTargetMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfMenuItem mUIDebugTargetMenuItem;
        #endregion
    }
}
